# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-25 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_pic', models.ImageField(upload_to='upload_pic')),
            ],
        ),
    ]
