# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-26 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagecfr_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='upload_pic',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
